//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewellery.Data.JewelleryDBEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JewelleryDBEntities : DbContext
    {
        public JewelleryDBEntities()
            : base("name=JewelleryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderState> OrderState { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Token> Token { get; set; }
        public virtual DbSet<OrderHistory> OrderHistory { get; set; }
    }
}
