//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewellery.Data.JewelleryDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderHistory = new HashSet<OrderHistory>();
            this.OrderState1 = new HashSet<OrderState>();
        }
    
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int AccountId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderTime { get; set; }
        public Nullable<int> ResponsibleAccountId { get; set; }
        public string OrderState { get; set; }
        public string Remarks { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderState> OrderState1 { get; set; }
    }
}
