//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewellery.Data.JewelleryDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderState
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int FromAccountId { get; set; }
        public int ToAccountId { get; set; }
        public string OrderState1 { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Remarks { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Order Order { get; set; }
    }
}
