//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewellery.Data.JewelleryDBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public int HID { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int AccountId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ResponsibleAccountId { get; set; }
        public string OrderState { get; set; }
        public string Remarks { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
